[book]
authors = ["Patrick Elsen"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-files book"

[preprocessor.files]
command = "cargo run --"
prefix = ".."

[output.html]
additional-css = ["style.css"]
